import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homescreen1</Link>
        </li>
        <li>
          <Link to="/small">Small</Link>
        </li>
        <li>
          <Link to="/openprofile">Openprofile</Link>
        </li>
        <li>
          <Link to="/profilecontactsone">ProfileContactsOne</Link>
        </li>
        <li>
          <Link to="/profilecontactscircles">ProfileContactsCircles</Link>
        </li>
        <li>
          <Link to="/profilecontacts">ProfileContacts</Link>
        </li>
        <li>
          <Link to="/profilecontactspinned">ProfileContactsPinned</Link>
        </li>
        <li>
          <Link to="/profilepinnedselect">ProfilePinnedSelect</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
